### ISSUE TITLE
Call "ls" with url and accents

### ISSUE THREAD

**Issue by GuillerVks** [evalEmpire/Alien-SVN#14]
Hello, 
I'm listing folder contents, but the url/path have accents, and svn return a error message: 

`subversion/libsvn_subr/dirent_uri.c:1500: uri_skip_ancestor: Assertion svn_uri_is_canonical(child_uri, ((void *)0))' failed.`

Code:

> my $last_rev = $svn->get_latest_revnum;
> my $list_refs = $ctx->ls( $url, $last_rev, 0)

My alternative at this moment is call with direct command, but i like can call by your library.

Thanks and sorry if i wrong to reporting.
Regards.

**Comment by jamessan** [comment]
Alien::SVN is just a means to installing Subversion's Perl bindings.  If you have an issue with their Perl bindings, you should take that discussion to their [user support list](https://subversion.apache.org/mailing-lists.html#users-ml).

**Comment by GuillerVks** [comment]
Ok, thanks @jamessan .
