### ISSUE TITLE
Non root install fails

### ISSUE THREAD

**Issue by davidedelvento** [evalEmpire/Alien-SVN#17]
Running `cpan SVN::Core` as normal user (non-root) will grab Alien-SVN-v1.8.11.0

Then answering the `Would you like to pass any arguments to configure?` question with `--libdir=/glade/apps/opt/perlmods/Alien/SVN --prefix=/glade/apps/opt/perlmods/` with the user having `/glade/apps/opt/perlmods/` writing permissions results in failed installation as follows. Why does it insist in trying to install in `/usr/local/lib64/perl5` despite the prefix?

```
Libraries have been installed in:
   /glade/apps/opt/perlmods/Alien/SVN

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
Running make install 
Files found in blib/arch: installing files in blib/lib into architecture dependent library tree
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: Can't create '/usr/local/lib64/perl5/SVN'
mkdir /usr/local/lib64/perl5: Permission denied at /usr/share/perl5/ExtUtils/Install.pm line 483

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 at -e line 1
make: *** [pure_site_install] Error 13
installing SVN::Core failed at inc/My/SVN/Builder.pm line 183.
  MSCHWERN/Alien-SVN-v1.8.11.0.tar.gz
  ./Build install  -- OK
Warning (usually harmless): 'YAML' not installed, will not store 
```

**Comment by schwern** [comment]
Those are configure options for the SVN library itself, sorry if that is not clear.

To get what you want, pass the normal Perl module configuration options to `Build.PL`.  You have a non-standard setup, but I believe it should be `perl Build.PL --install_base /glade/apps/opt/ --install_path lib=/glade/apps/opt/perlmods/`.  Then take the default configure options, they should have the appropriate `--prefix` and `--libdir` already set.

If it doesn't work, try starting with a fresh unpack of the source; I'm not 100% sure that re-running `Build.PL` will completely reset everything.

Let me know how it goes.  If it doesn't work, please show me the whole build transcript.  It'll be long, but it'll make things faster if I can see the whole thing.  Use gist.github.com or similar paste bin.

**Comment by davidedelvento** [comment]
Thanks so much for the quick answer. I've downloaded the tarball and ran 

`perl Build.PL --install_base /glade/apps/opt/perlmods --install_path lib=/glade/apps/opt/perlmods/.`

`./Build`

And that succeeded (however building succeeded when installing with cpan too). Now what? There is no makefile against which to run `make install`, nor grepping `install` into `Build.*` finds anything, nor the README tells anything. I'm not sure if this is trivial question, I am not a perl user, I am actually installing this as a dependency for another thing, which is a dependency for another thing (see http://www.xkcd.com/1579/ for details)

**Comment by schwern** [comment]
Next is `./Build test` then `./Build install`.  This module uses [Module::Build](https://metacpan.org/pod/Module::Build).  It's one of the two standard ways to build Perl modules so it doesn't bother with an INSTALL document, but one wouldn't hurt.

> perl Build.PL --install_base /glade/apps/opt/perlmods --install_path lib=/glade/apps/opt/perlmods/.

That will mix man pages with your Perl modules, you probably don't want that.  That should be `--install_base /glade/apps/opt/ --install_path lib=/glade/apps/opt/perlmods/`.  `--install_base` is like `--prefix` (Perl doesn't use `--prefix` for historical reasons) and `--install_path lib` is like `--libdir`.  [Here is more about how to control installation](https://metacpan.org/pod/Module::Build#INSTALL-PATHS).

**Comment by davidedelvento** [comment]
Ok, this way, I was able to install. I still have troubles to use it since setting only PERL5LIB doesn't seem to suffice, but I guess this is even more related to my ignorance of perl than the initial part of this ticket. You may close this ticket -- thanks for your help.

**Comment by schwern** [comment]
Sorry for the trouble, but I agree that this is now a generic Perl module installation problem.  Try stackoverflow.com?
